package info.kimjihyok.new_york_times_client.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import info.kimjihyok.new_york_times_client.db.PostItem;
import info.kimjihyok.new_york_times_client.db.Multimedia;

import info.kimjihyok.new_york_times_client.db.PostItemDao;
import info.kimjihyok.new_york_times_client.db.MultimediaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postItemDaoConfig;
    private final DaoConfig multimediaDaoConfig;

    private final PostItemDao postItemDao;
    private final MultimediaDao multimediaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postItemDaoConfig = daoConfigMap.get(PostItemDao.class).clone();
        postItemDaoConfig.initIdentityScope(type);

        multimediaDaoConfig = daoConfigMap.get(MultimediaDao.class).clone();
        multimediaDaoConfig.initIdentityScope(type);

        postItemDao = new PostItemDao(postItemDaoConfig, this);
        multimediaDao = new MultimediaDao(multimediaDaoConfig, this);

        registerDao(PostItem.class, postItemDao);
        registerDao(Multimedia.class, multimediaDao);
    }
    
    public void clear() {
        postItemDaoConfig.getIdentityScope().clear();
        multimediaDaoConfig.getIdentityScope().clear();
    }

    public PostItemDao getPostItemDao() {
        return postItemDao;
    }

    public MultimediaDao getMultimediaDao() {
        return multimediaDao;
    }

}
