package info.kimjihyok.new_york_times_client.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.SerializedName;

import java.util.List;
// KEEP INCLUDES END


/**
 * Entity mapped to table "POST_ITEM".
 */
public class PostItem {

    private Long id;
    private String section;
    private String subsection;
    private String title;
    private String url;
    private String byline;
    private String updated_date;
    private String created_date;
    private String published_date;
    private String material_type_facet;
    private String kicker;

    // KEEP FIELDS - put your custom fields here
    @SerializedName("abstract")
    private String abstract_string;

    private List<Multimedia> multimedia;

    //Ignore these fields when serializing
    private transient String des_facet;
    private transient String org_facet;
    private transient String per_facet;
    private transient String geo_facet;
    // KEEP FIELDS END

    public PostItem() {
    }

    public PostItem(Long id) {
        this.id = id;
    }

    public PostItem(Long id, String section, String subsection, String title, String url, String byline, String updated_date, String created_date, String published_date, String material_type_facet, String kicker, String des_facet, String org_facet, String per_facet, String geo_facet) {
        this.id = id;
        this.section = section;
        this.subsection = subsection;
        this.title = title;
        this.url = url;
        this.byline = byline;
        this.updated_date = updated_date;
        this.created_date = created_date;
        this.published_date = published_date;
        this.material_type_facet = material_type_facet;
        this.kicker = kicker;
        this.des_facet = des_facet;
        this.org_facet = org_facet;
        this.per_facet = per_facet;
        this.geo_facet = geo_facet;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSection() {
        return section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public String getSubsection() {
        return subsection;
    }

    public void setSubsection(String subsection) {
        this.subsection = subsection;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getByline() {
        return byline;
    }

    public void setByline(String byline) {
        this.byline = byline;
    }

    public String getUpdated_date() {
        return updated_date;
    }

    public void setUpdated_date(String updated_date) {
        this.updated_date = updated_date;
    }

    public String getCreated_date() {
        return created_date;
    }

    public void setCreated_date(String created_date) {
        this.created_date = created_date;
    }

    public String getPublished_date() {
        return published_date;
    }

    public void setPublished_date(String published_date) {
        this.published_date = published_date;
    }

    public String getMaterial_type_facet() {
        return material_type_facet;
    }

    public void setMaterial_type_facet(String material_type_facet) {
        this.material_type_facet = material_type_facet;
    }

    public String getKicker() {
        return kicker;
    }

    public void setKicker(String kicker) {
        this.kicker = kicker;
    }


    // KEEP METHODS - put your custom methods here
    public String getAbstract() {
        return abstract_string;
    }

    public void setAbstract(String abstract_string) {
        this.abstract_string = abstract_string;
    }

    public List<Multimedia> getMultimedia() {
        return multimedia;
    }

    public void setMultimedia(List<Multimedia> multimedia) {
        this.multimedia = multimedia;
    }

    public String getDes_facet() {
        return des_facet;
    }

    public void setDes_facet(String des_facet) {
        this.des_facet = des_facet;
    }

    public String getOrg_facet() {
        return org_facet;
    }

    public void setOrg_facet(String org_facet) {
        this.org_facet = org_facet;
    }

    public String getPer_facet() {
        return per_facet;
    }

    public void setPer_facet(String per_facet) {
        this.per_facet = per_facet;
    }

    public String getGeo_facet() {
        return geo_facet;
    }

    public void setGeo_facet(String geo_facet) {
        this.geo_facet = geo_facet;
    }
    // KEEP METHODS END

}
